ER\CantineBundle\Entity\Course:
    type: entity
    table: null
    repositoryClass: ER\CantineBundle\Repository\CourseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        datecourse:
            type: datetime
        prix:
            type: float
    manyToOne:
        utilisateur:
            targetEntity: Utilisateur
            inversedBy: courses