<?php

namespace ER\CantineBundle\Repository;

/**
 * MiseajourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiseajourRepository extends \Doctrine\ORM\EntityRepository {

    public function findLastUpdate() {
        
        $dql = "select max(m.datemaj) from ER\CantineBundle\Entity\Miseajour m";
        $query = $this->_em->createQuery($dql);
        $max = $query
                ->getSingleScalarResult();

        return $max;
   
}
}
