<?php

namespace ER\CantineBundle\Repository;

/**
 * MiseajourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiseajourRepository extends \Doctrine\ORM\EntityRepository {

    public function findLastUpdate() {
        $query = $this->_em->createQuery("SELECT MAX(m) FROM ERCantineBundle:Miseajour m ");
        $max = $query
                ->getResult();

        return $max;
    }

}
