<?php

namespace ER\CantineBundle\Repository;

/**
 * MiseajourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiseajourRepository extends \Doctrine\ORM\EntityRepository
{
                public function findLastUpdate(){
        $dql = "SELECT MAX(m) FROM ER\CantineBundle\Entity\Miseajour m ";
                $max = $this->_em->createQuery($dql)
              ->getResult();
               return $max;
    }
    
    
    
}
