<?php

namespace ER\CantineBundle\Repository;

/**
 * RepasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasRepository extends \Doctrine\ORM\EntityRepository {

    public function findNbRepasByDate($date1, $date2) {
        $dql = "SELECT COUNT(r.id) FROM ER\CantineBundle\Entity\Repas r WHERE r.daterepas  BETWEEN '$date1' and '$date2'";
        $count = $this->_em->createQuery($dql)
                ->getSingleScalarResult();
        return $count;
    }

    public function findNbRepasByUser($date1, $date2, $user) {

        $dql = "SELECT COUNT(r.id) FROM ER\CantineBundle\Entity\Repas r WHERE r.etat = 'valid' AND(r.utilisateur = $user) AND(r.daterepas  BETWEEN '$date1' and '$date2')";
        $repas = $this->_em->createQuery($dql)
                ->getSingleScalarResult();
        return $repas;
    }

    public function findNbRepasByEtatAndDate($date1, $date2, $etat) {
        $dql = "SELECT COUNT(r.id) FROM ER\CantineBundle\Entity\Repas r WHERE r.etat = '$etat' AND(r.daterepas BETWEEN '$date1' and '$date2') ";
        $count = $this->_em->createQuery($dql)
                ->getSingleScalarResult();
        return $count;
    }

    public function findRepasBydate($date1, $date2) {
        $dql = "SELECT r FROM ER\CantineBundle\Entity\Repas r WHERE r.daterepas BETWEEN '$date1' and '$date2'";
        $repas = $this->_em->createQuery($dql)
                ->getResult();
        return $repas;
    }

    public function findRepasBydateAndUtilisateur($date1, $date2, $userid) {
        $dql = "SELECT r FROM ER\CantineBundle\Entity\Repas r WHERE r.utilisateur = $userid AND(r.daterepas BETWEEN '$date1' and '$date2')";
        $repas = $this->_em->createQuery($dql)
                ->getResult();
        return $repas;
    }

    public function findNbrepasByUserBetween($date1, $date2, $user) {
        $dql = "SELECT COUNT(r.id) FROM ER\CantineBundle\Entity\Repas r WHERE r.utilisateur=$user AND(r.daterepas BETWEEN '$date1' and '$date2')";
        $countrepas = $this->_em->createQuery($dql)
                ->getResult();
        return $countrepas;
    }

}
