<?php

namespace ER\CantineBundle\Repository;

/**
 * RepasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasRepository extends \Doctrine\ORM\EntityRepository
{
        public function findNbRepas(){
        $dql = "SELECT COUNT(r.id) FROM ER\CantineBundle\Entity\Repas r ";
                $count = $this->_em->createQuery($dql)
              ->getSingleScalarResult();
                    return $count;
    }
            public function findNbRepasByEtatMange(){
        $dql = "SELECT COUNT(r.id) FROM ER\CantineBundle\Entity\Repas r WHERE r.etat = 'mange'";
                $count = $this->_em->createQuery($dql)
              ->getSingleScalarResult();
                    return $count;
    }
    

}
