<?php

namespace ER\CantineBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository {

            public function findNbRepasByUser(){
        $dql = "SELECT COUNT() FROM ER\CantineBundle\Entity\Repas u where u.repas.etat = 'valid'";
                $count = $this->_em->createQuery($dql)
              ->getSingleScalarResult();
                
                    return $count;
            }

}
